// Code generated by scg 1,  DO NOT EDIT .
//
// LemonadeGame-Consts with name of scene text for
//
// Command:
// scg
// DO NOT EDIT .

package textsname

type SceneTextName string

const (

	// ApproveEndDayText and ApproveEndDayTTS of text for ApproveEndDay scene
	ApproveEndDayText = "LemonadeGame-ApproveEndDayText"
	ApproveEndDayTTS  = "LemonadeGame-ApproveEndDayTTS"

	// BugsInfoText and BugsInfoTTS of text for BugsInfo scene
	BugsInfoText = "LemonadeGame-BugsInfoText"
	BugsInfoTTS  = "LemonadeGame-BugsInfoTTS"

	// BugsSaleText and BugsSaleTTS of text for BugsSale scene
	BugsSaleText = "LemonadeGame-BugsSaleText"
	BugsSaleTTS  = "LemonadeGame-BugsSaleTTS"

	// DropsInfoText and DropsInfoTTS of text for DropsInfo scene
	DropsInfoText = "LemonadeGame-DropsInfoText"
	DropsInfoTTS  = "LemonadeGame-DropsInfoTTS"

	// DropsSaleText and DropsSaleTTS of text for DropsSale scene
	DropsSaleText = "LemonadeGame-DropsSaleText"
	DropsSaleTTS  = "LemonadeGame-DropsSaleTTS"

	// EndGameText and EndGameTTS of text for EndGame scene
	EndGameText = "LemonadeGame-EndGameText"
	EndGameTTS  = "LemonadeGame-EndGameTTS"

	// EndOfDayText and EndOfDayTTS of text for EndOfDay scene
	EndOfDayText = "LemonadeGame-EndOfDayText"
	EndOfDayTTS  = "LemonadeGame-EndOfDayTTS"

	// FlyInfoText and FlyInfoTTS of text for FlyInfo scene
	FlyInfoText = "LemonadeGame-FlyInfoText"
	FlyInfoTTS  = "LemonadeGame-FlyInfoTTS"

	// FlySaleText and FlySaleTTS of text for FlySale scene
	FlySaleText = "LemonadeGame-FlySaleText"
	FlySaleTTS  = "LemonadeGame-FlySaleTTS"

	// GoodbyeText and GoodbyeTTS of text for Goodbye scene
	GoodbyeText = "LemonadeGame-GoodbyeText"
	GoodbyeTTS  = "LemonadeGame-GoodbyeTTS"

	// GreenhouseInfoText and GreenhouseInfoTTS of text for GreenhouseInfo scene
	GreenhouseInfoText = "LemonadeGame-GreenhouseInfoText"
	GreenhouseInfoTTS  = "LemonadeGame-GreenhouseInfoTTS"

	// GreenhouseSaleText and GreenhouseSaleTTS of text for GreenhouseSale scene
	GreenhouseSaleText = "LemonadeGame-GreenhouseSaleText"
	GreenhouseSaleTTS  = "LemonadeGame-GreenhouseSaleTTS"

	// HealInfoText and HealInfoTTS of text for HealInfo scene
	HealInfoText = "LemonadeGame-HealInfoText"
	HealInfoTTS  = "LemonadeGame-HealInfoTTS"

	// HealSaleText and HealSaleTTS of text for HealSale scene
	HealSaleText = "LemonadeGame-HealSaleText"
	HealSaleTTS  = "LemonadeGame-HealSaleTTS"

	// HelloText and HelloTTS of text for Hello scene
	HelloText = "LemonadeGame-HelloText"
	HelloTTS  = "LemonadeGame-HelloTTS"

	// IsStartText and IsStartTTS of text for IsStart scene
	IsStartText = "LemonadeGame-IsStartText"
	IsStartTTS  = "LemonadeGame-IsStartTTS"

	// NewDayText and NewDayTTS of text for NewDay scene
	NewDayText = "LemonadeGame-NewDayText"
	NewDayTTS  = "LemonadeGame-NewDayTTS"

	// RulesText and RulesTTS of text for Rules scene
	RulesText = "LemonadeGame-RulesText"
	RulesTTS  = "LemonadeGame-RulesTTS"

	// ShopText and ShopTTS of text for Shop scene
	ShopText = "LemonadeGame-ShopText"
	ShopTTS  = "LemonadeGame-ShopTTS"

	// StartRulesText and StartRulesTTS of text for StartRules scene
	StartRulesText = "LemonadeGame-StartRulesText"
	StartRulesTTS  = "LemonadeGame-StartRulesTTS"
)
