// Code generated by scg 1,  DO NOT EDIT .
//
// LemonadeGame Interface for script text manager
//
// Command:
// scg
// DO NOT EDIT .

package manager

import "github.com/ThCompiler/go_game_constractor/director/scene"

type TextManager interface {

	// GetApproveEndDayText get text for approveEndDay scene with variables
	GetApproveEndDayText() (scene.Text, error)

	// GetBugsInfoText get text for bugsInfo scene with variables
	GetBugsInfoText() (scene.Text, error)

	// GetBugsSaleText get text for bugsSale scene with variables
	GetBugsSaleText(bugsCost uint64) (scene.Text, error)

	// GetDropsInfoText get text for dropsInfo scene with variables
	GetDropsInfoText(dropsCount uint64) (scene.Text, error)

	// GetDropsSaleText get text for dropsSale scene with variables
	GetDropsSaleText() (scene.Text, error)

	// GetEndGameText get text for endGame scene with variables
	GetEndGameText(score uint64) (scene.Text, error)

	// GetEndOfDayText get text for endOfDay scene with variables
	GetEndOfDayText(balance uint64, livesCount uint64, petalsCount uint64) (scene.Text, error)

	// GetFlyInfoText get text for flyInfo scene with variables
	GetFlyInfoText() (scene.Text, error)

	// GetFlySaleText get text for flySale scene with variables
	GetFlySaleText(flyCost uint64) (scene.Text, error)

	// GetGoodbyeText get text for goodbye scene with variables
	GetGoodbyeText() (scene.Text, error)

	// GetGreenhouseInfoText get text for greenhouseInfo scene with variables
	GetGreenhouseInfoText() (scene.Text, error)

	// GetGreenhouseSaleText get text for greenhouseSale scene with variables
	GetGreenhouseSaleText(greenhouseCost uint64) (scene.Text, error)

	// GetHealInfoText get text for healInfo scene with variables
	GetHealInfoText() (scene.Text, error)

	// GetHealSaleText get text for healSale scene with variables
	GetHealSaleText() (scene.Text, error)

	// GetHelloText get text for hello scene with variables
	GetHelloText() (scene.Text, error)

	// GetIsStartText get text for is_start scene with variables
	GetIsStartText() (scene.Text, error)

	// GetNewDayText get text for newDay scene with variables
	GetNewDayText() (scene.Text, error)

	// GetRulesText get text for rules scene with variables
	GetRulesText() (scene.Text, error)

	// GetShopText get text for shop scene with variables
	GetShopText(bugsCost uint64, flyCost uint64, greenhouseCost uint64, healCost uint64) (scene.Text, error)

	// GetStartRulesText get text for start_rules scene with variables
	GetStartRulesText() (scene.Text, error)
}
