// Code generated by scg 1,  DO NOT EDIT .
//
// BotanicalGardenGame-Custom user text errors
//
// Command:
// scg
// DO NOT EDIT .

package errors

import "github.com/ThCompiler/go_game_constractor/director/scene"

// text errors
var (
	NotUnderstandHealSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить аптечку?"}

// >>>>>>> Generated 
// 	NotUnderstandEndGameError = scene.BaseTextError{Message: "Я не понимаю о чём вы"}
// >>>>>>> Generated 
	NotUnderstandApproveEndDayError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Вы точно хотите закончить день?"}

	NotUnderstandEndOfDayError = scene.BaseTextError{Message: "Я не понимаю о чём вы"}

	NotUnderstandFlySaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить защиту от ветра?"}

	NotUnderstandError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Согласены ли вы поиграть?)"}

// >>>>>>> Generated 
// 	NotUnderstandFlySaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить защиту от ветра?"}
// >>>>>>> Generated 
	NotUnderstandDropsSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Либо я не знаю такого положительного числа. Либо вы хотели сказать что-то другое"}

// >>>>>>> Generated 
// 	NotUnderstandGreenhouseSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить теплицу?"}
// >>>>>>> Generated 
	NotUnderstandEndGameError = scene.BaseTextError{Message: "Я не понимаю о чём вы"}

// >>>>>>> Generated 
// 	NotUnderstandFlySaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить защиту от ветра?"}
// >>>>>>> Generated 
	NotUnderstandBugsSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить защиту от жуков?"}

	YouAboutWhatError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Что вы хотите купить? Или может хотите выйти?"}

// >>>>>>> Generated 
// 	NotUnderstandDropsSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Либо я не знаю такого положительного числа. Либо вы хотели сказать что-то другое"}
// 
// 	NotUnderstandBugsSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить защиту от жуков?"}
// 
// 	NotUnderstandApproveEndDayError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Вы точно хотите закончить день?"}
// 
// 	NotUnderstandEndOfDayError = scene.BaseTextError{Message: "Я не понимаю о чём вы"}
// >>>>>>> Generated 
	NotUnderstandGreenhouseSaleError = scene.BaseTextError{Message: "Я не понимаю о чём вы. Хотите ли вы купить теплицу?"}
)
