// Code generated by scg 1, .
//
// BotanicalGardenGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
    "github.com/ThCompiler/go_game_constractor/director"
    "github.com/ThCompiler/go_game_constractor/director/scriptdirector/scene"
    base_matchers "github.com/ThCompiler/go_game_constractor/director/scriptdirector/matchers"
    "github.com/evrone/go-clean-template/pkg/game/scg/botanicalgardengame/manager"
    "github.com/evrone/go-clean-template/pkg/game/scg/botanicalgardengame/script/errors"
)

const (
    // AgreeIsStartButtonText - text for button Agree
    AgreeIsStartButtonText = "Точно"
)

// IsStart scene
type IsStart struct {
    TextManager manager.TextManager
    NextScene   SceneName
}

// React function of actions after scene has been played
func (sc *IsStart) React(ctx *scene.Context) scene.Command {
    switch {
    // Buttons select
    case ctx.Request.NameMatched == AgreeIsStartButtonText && ctx.Request.WasButton:
        sc.NextScene = ShopScene
        // Matcher select
    case ctx.Request.NameMatched == base_matchers.AgreeMatchedString:
        sc.NextScene = ShopScene
    }
    return scene.NoCommand
}

// Next function returning next scene
func (sc *IsStart) Next() scene.Scene {
    switch sc.NextScene {
    case ShopScene:
        return &Shop{
            TextManager: sc.TextManager,
        }
    }

    return &IsStart{
        TextManager: sc.TextManager,
    }
}

// GetSceneInfo function returning info about scene
func (sc *IsStart) GetSceneInfo(_ *scene.Context) (scene.Info, bool) {
    text, _ := sc.TextManager.GetIsStartText()
    return scene.Info{
        Text: text,
        ExpectedMessages: []scene.MessageMatcher{
            base_matchers.Agree,
        },
        Buttons: []director.Button{
            {
                Title: AgreeIsStartButtonText,
            },
        },
        Err: errors.NotUnderstandError,
    }, true
}
