// Code generated by scg 1,  DO NOT EDIT .
//
// BotanicalGardenGame-Scenes Name
//
// Command:
// scg
// DO NOT EDIT .

package scenes

type SceneName string

const (
	// ApproveEndDayScene name of $nameScene
	ApproveEndDayScene = SceneName("approve_end_day")
	// BugsInfoScene name of $nameScene
	BugsInfoScene = SceneName("bugs_info")
	// BugsSaleScene name of $nameScene
	BugsSaleScene = SceneName("bugs_sale")
	// DropsInfoScene name of $nameScene
	DropsInfoScene = SceneName("drops_info")
	// DropsSaleScene name of $nameScene
	DropsSaleScene = SceneName("drops_sale")
	// EndGameScene name of $nameScene
	EndGameScene = SceneName("end_game")
	// EndOfDayScene name of $nameScene
	EndOfDayScene = SceneName("end_of_day")
	// FlyInfoScene name of $nameScene
	FlyInfoScene = SceneName("fly_info")
	// FlySaleScene name of $nameScene
	FlySaleScene = SceneName("fly_sale")
	// GoodbyeScene name of $nameScene
	GoodbyeScene = SceneName("goodbye")
	// GreenhouseInfoScene name of $nameScene
	GreenhouseInfoScene = SceneName("greenhouse_info")
	// GreenhouseSaleScene name of $nameScene
	GreenhouseSaleScene = SceneName("greenhouse_sale")
	// HealInfoScene name of $nameScene
	HealInfoScene = SceneName("heal_info")
	// HealSaleScene name of $nameScene
	HealSaleScene = SceneName("heal_sale")
	// HelloScene name of $nameScene
	HelloScene = SceneName("hello")
	// IsStartScene name of $nameScene
	IsStartScene = SceneName("is_start")
	// NewDayScene name of $nameScene
	NewDayScene = SceneName("new_day")
	// RulesScene name of $nameScene
	RulesScene = SceneName("rules")
	// ShopScene name of $nameScene
	ShopScene = SceneName("shop")
	// StartRulesScene name of $nameScene
	StartRulesScene = SceneName("start_rules")
	// NoScene name of next scene for ending scenes
	NoScene = SceneName("_nothing_scene")
)
