// Code generated by scg 1, .
//
// LemonadeGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
    "github.com/ThCompiler/go_game_constractor/director"
    "github.com/ThCompiler/go_game_constractor/director/scriptdirector/scene"
    "github.com/evrone/go-clean-template/pkg/game/scg/lemonadegame/manager"
)

// DropsInfo scene
type DropsInfo struct {
    TextManager manager.TextManager
    NextScene   SceneName
}

// React function of actions after scene has been played
func (sc *DropsInfo) React(_ *scene.Context) scene.Command {
    return scene.NoCommand
}

// Next function returning next scene
func (sc *DropsInfo) Next() scene.Scene {
    return &Shop{
        TextManager: sc.TextManager,
    }
}

// GetSceneInfo function returning info about scene
func (sc *DropsInfo) GetSceneInfo(_ *scene.Context) (scene.Info, bool) {
    var (
        dropsCount uint64
    )

    // TODO Write some actions for get data for texts

    text, _ := sc.TextManager.GetDropsInfoText(
        dropsCount,
    )
    return scene.Info{
        Text:             text,
        ExpectedMessages: []scene.MessageMatcher{},
        Buttons:          []director.Button{},
    }, false
}
