// Code generated by scg 1, .
//
// LemonadeGame-SceneStructs
//
// Command:
// scg
//.

package scenes

import (
    "github.com/ThCompiler/go_game_constractor/director"
    base_matchers "github.com/ThCompiler/go_game_constractor/director/scriptdirector/matchers"
    "github.com/ThCompiler/go_game_constractor/director/scriptdirector/scene"
    "github.com/evrone/go-clean-template/pkg/game/scg/lemonadegame/manager"
    "github.com/evrone/go-clean-template/pkg/game/scg/lemonadegame/script/errors"
    "github.com/evrone/go-clean-template/pkg/game/scg/lemonadegame/script/matchers"
)

const (
    // AgreeHealSaleButtonText - text for button Agree
    AgreeHealSaleButtonText = "Ага"
    // BackHealSaleButtonText - text for button Back
    BackHealSaleButtonText = "Нет"
)

// HealSale scene
type HealSale struct {
    TextManager manager.TextManager
    NextScene   SceneName
}

// React function of actions after scene has been played
func (sc *HealSale) React(ctx *scene.Context) scene.Command {
    // TODO Write the actions after HealSale scene has been played
    switch {
    // Buttons select
    case ctx.Request.NameMatched == AgreeHealSaleButtonText && ctx.Request.WasButton:

    case ctx.Request.NameMatched == BackHealSaleButtonText && ctx.Request.WasButton:

        // Matcher select
    case ctx.Request.NameMatched == base_matchers.AgreeMatchedString:

    case ctx.Request.NameMatched == matchers.BackMatchedString:

    }

    sc.NextScene = HealSaleScene // TODO: manually set next scene after reaction
    return scene.NoCommand
}

// Next function returning next scene
func (sc *HealSale) Next() scene.Scene {
    switch sc.NextScene {
    case ShopScene:
        return &Shop{
            TextManager: sc.TextManager,
        }
    case HealInfoScene:
        return &HealInfo{
            TextManager: sc.TextManager,
        }
    }

    return &HealSale{
        TextManager: sc.TextManager,
    }
}

// GetSceneInfo function returning info about scene
func (sc *HealSale) GetSceneInfo(_ *scene.Context) (scene.Info, bool) {

    // TODO Write some actions for get data for texts

    text, _ := sc.TextManager.GetHealSaleText()
    return scene.Info{
        Text: text,
        ExpectedMessages: []scene.MessageMatcher{
            base_matchers.Agree,
            matchers.BackMatcher,
        },
        Buttons: []director.Button{
            {
                Title: AgreeHealSaleButtonText,
            },
            {
                Title: BackHealSaleButtonText,
            },
        },
        Err: errors.NotUnderstandHealSaleError,
    }, true
}
