// Code generated by scg 1,  DO NOT EDIT .
//
// BotanicalGardenGame-Consts with name of scene text for
//
// Command:
// scg
// DO NOT EDIT .

package textsname

type SceneTextName string

const (

	// ApproveEndDayText and ApproveEndDayTTS of text for ApproveEndDay scene
	ApproveEndDayText = "BotanicalGardenGame-ApproveEndDayText"
	ApproveEndDayTTS  = "BotanicalGardenGame-ApproveEndDayTTS"

	// BugsInfoText and BugsInfoTTS of text for BugsInfo scene
	BugsInfoText = "BotanicalGardenGame-BugsInfoText"
	BugsInfoTTS  = "BotanicalGardenGame-BugsInfoTTS"

	// BugsSaleText and BugsSaleTTS of text for BugsSale scene
	BugsSaleText = "BotanicalGardenGame-BugsSaleText"
	BugsSaleTTS  = "BotanicalGardenGame-BugsSaleTTS"

	// DropsInfoText and DropsInfoTTS of text for DropsInfo scene
	DropsInfoText = "BotanicalGardenGame-DropsInfoText"
	DropsInfoTTS  = "BotanicalGardenGame-DropsInfoTTS"

	// DropsSaleText and DropsSaleTTS of text for DropsSale scene
	DropsSaleText = "BotanicalGardenGame-DropsSaleText"
	DropsSaleTTS  = "BotanicalGardenGame-DropsSaleTTS"

	// EndGameText and EndGameTTS of text for EndGame scene
	EndGameText = "BotanicalGardenGame-EndGameText"
	EndGameTTS  = "BotanicalGardenGame-EndGameTTS"

	// EndOfDayText and EndOfDayTTS of text for EndOfDay scene
	EndOfDayText = "BotanicalGardenGame-EndOfDayText"
	EndOfDayTTS  = "BotanicalGardenGame-EndOfDayTTS"

	// FlyInfoText and FlyInfoTTS of text for FlyInfo scene
	FlyInfoText = "BotanicalGardenGame-FlyInfoText"
	FlyInfoTTS  = "BotanicalGardenGame-FlyInfoTTS"

	// FlySaleText and FlySaleTTS of text for FlySale scene
	FlySaleText = "BotanicalGardenGame-FlySaleText"
	FlySaleTTS  = "BotanicalGardenGame-FlySaleTTS"

	// GoodbyeText and GoodbyeTTS of text for Goodbye scene
	GoodbyeText = "BotanicalGardenGame-GoodbyeText"
	GoodbyeTTS  = "BotanicalGardenGame-GoodbyeTTS"

	// GreenhouseInfoText and GreenhouseInfoTTS of text for GreenhouseInfo scene
	GreenhouseInfoText = "BotanicalGardenGame-GreenhouseInfoText"
	GreenhouseInfoTTS  = "BotanicalGardenGame-GreenhouseInfoTTS"

	// GreenhouseSaleText and GreenhouseSaleTTS of text for GreenhouseSale scene
	GreenhouseSaleText = "BotanicalGardenGame-GreenhouseSaleText"
	GreenhouseSaleTTS  = "BotanicalGardenGame-GreenhouseSaleTTS"

	// HealInfoText and HealInfoTTS of text for HealInfo scene
	HealInfoText = "BotanicalGardenGame-HealInfoText"
	HealInfoTTS  = "BotanicalGardenGame-HealInfoTTS"

	// HealSaleText and HealSaleTTS of text for HealSale scene
	HealSaleText = "BotanicalGardenGame-HealSaleText"
	HealSaleTTS  = "BotanicalGardenGame-HealSaleTTS"

	// HelloText and HelloTTS of text for Hello scene
	HelloText = "BotanicalGardenGame-HelloText"
	HelloTTS  = "BotanicalGardenGame-HelloTTS"

	// IsStartText and IsStartTTS of text for IsStart scene
	IsStartText = "BotanicalGardenGame-IsStartText"
	IsStartTTS  = "BotanicalGardenGame-IsStartTTS"

	// NewDayText and NewDayTTS of text for NewDay scene
	NewDayText = "BotanicalGardenGame-NewDayText"
	NewDayTTS  = "BotanicalGardenGame-NewDayTTS"

	// RulesText and RulesTTS of text for Rules scene
	RulesText = "BotanicalGardenGame-RulesText"
	RulesTTS  = "BotanicalGardenGame-RulesTTS"

	// ShopText and ShopTTS of text for Shop scene
	ShopText = "BotanicalGardenGame-ShopText"
	ShopTTS  = "BotanicalGardenGame-ShopTTS"

	// StartRulesText and StartRulesTTS of text for StartRules scene
	StartRulesText = "BotanicalGardenGame-StartRulesText"
	StartRulesTTS  = "BotanicalGardenGame-StartRulesTTS"
)
